// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgwcpmzmfsbzrlmrugit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nd2NwbXptZnNienJsbXJ1Z2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzg1MTcsImV4cCI6MjA2NDkxNDUxN30.YIULoz7pDUwGCtvuxjoxbXPFsG6L5hST8oxF6o9WUCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);